### ISSUE TITLE
Implement reload between shots mechanic

### ISSUE THREAD

**Issue by kevincerro-dvrv** [kevincerro-dvrv/canon-defense#2]
After each shot, the cannon undergoes a quick 2-second reloading process. This allows players to maintain a continuous rate of fire during active engagements. The short reload time encourages a fast-paced and action-packed experience, enabling players to respond swiftly to incoming enemies.

**Comment by aryankharbanda** [comment]
Have implemented, will push after previous PR merge, but isn't 2 second going to make the game very slow paced?
